language: r
cache: packages
dist: xenial
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
env:
  TEST_R_WITH_ARROW: "TRUE"
  ARROW_USE_OLD_CXXABI: 1
before_install:
# Set this in .Rprofile for RSPM binary packages
- echo 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))' >> ~/.Rprofile.site
- sudo apt-get install -y gdb
# Download binaries
- wget https://dl.bintray.com/nealrichardson/pyarrow-dev/libarrow.zip
- unzip *.zip
- git clone https://github.com/nealrichardson/arrow.git
- cd arrow/r
# Checkout the same commit as where the wheel was made
- git checkout kszucs-dataset
before_script:
- export INCLUDE_DIR=$TRAVIS_BUILD_DIR/build/include
- export LIB_DIR=$TRAVIS_BUILD_DIR/build/lib
- export LD_LIBRARY_PATH=$LIB_DIR
- R -e 'install.packages("Rcpp", repo="https://cloud.r-project.org/")'
script:
- R CMD INSTALL --install-tests .
- R --debugger=gdb --debugger-args="-batch -x ../../bt.gdb" --slave -e 'library(testthat); setwd(file.path(.libPaths()[1], "arrow", "tests")); test_check("arrow", reporter="summary")'
