language: r
cache: packages
dist: xenial
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
env:
  TEST_R_WITH_ARROW: "TRUE"
  ARROW_USE_OLD_CXXABI: 1
before_install:
- echo 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))' >> ~/.Rprofile.site
- wget https://files.pythonhosted.org/packages/7c/a5/5e1edbe3cc3487279828cf201793b16f7392493c8e68fe8bafc018829709/pyarrow-0.14.1-cp27-cp27mu-manylinux1_x86_64.whl
- unzip *.whl
- git clone --depth=1 https://github.com/nealrichardson/arrow.git -b 0.14.1.1-rpkg
- cd arrow/r
before_script:
- export INCLUDE_DIR=$TRAVIS_BUILD_DIR/pyarrow/include
- export LIB_DIR=$TRAVIS_BUILD_DIR/pyarrow
- export LD_LIBRARY_PATH=$LIB_DIR
