language: r
cache: packages
dist: xenial
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
env:
  TEST_R_WITH_ARROW: "TRUE"
before_install:
# Set this in .Rprofile for RSPM binary packages
- echo 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))' >> ~/.Rprofile.site
- sudo apt-get install -y gdb
# Download wheel
- wget https://dl.bintray.com/nealrichardson/pyarrow-dev/pyarrow-0.15.1.dev392+g1f7e7f852.d20191205-cp37-cp37m-manylinux2014_x86_64.whl
- unzip *.whl
- git clone https://github.com/apache/arrow.git
- cd arrow/r
# Checkout the same commit as where the wheel was made
- git checkout 1f7e7f852baf01f335be45fca8cc2c5f3f0f2d01
before_script:
- export INCLUDE_DIR=$TRAVIS_BUILD_DIR/pyarrow/include
- export LIB_DIR=$TRAVIS_BUILD_DIR/pyarrow
- export LD_LIBRARY_PATH=$LIB_DIR
- R -e 'install.packages("Rcpp", repo="https://cloud.r-project.org/")'
script:
- R CMD INSTALL --install-tests .
- R --debugger=gdb --debugger-args="-batch -x ../../bt.gdb" --slave -e 'library(testthat); setwd(file.path(.libPaths()[1], "arrow", "tests")); test_check("arrow", reporter="summary")'
