language: generic
dist: xenial
before_script:
- sudo snap install hub --classic
script:
- source hub.sh
env:
  global:
    secure: qqtRL71Dhp3SqbCgRNBDdz2mZrBYMutOS+vXcevbLhnTtWggF3UX2dtlfHYqklYU+njD1RHbML+nxpZy2W8XyZuj7Os12/BBey3PEwdJAPVP6eEYRDQ3ZTeVkX8TUJy8T9kgZbEa3kZl3u5FbA4Yt5irbHyWVmXaGl+3zBTP3zXh6H92UrBvXd7gbi0kLW4bMVlWE06u4tQhqIK6rx8EF+WheRaDGGg8hWSucvyVWP7n6btvK1xj1RnTDmGT1ZX2FvMIgRVmOliXyxywprurk0ZPbG9512wkiB21MjRJa1FMxphO3FTZQKxgpJQ9BCCMUlYeLrvJLPeGtYU70b8c0e5HP55jf0+sHrD0Dodz1RG/18l3Uz6fovM5KLcETAam5Zs4gm0PwapalQAO2P+QWj2FRIVb0qUWz34psDz8WqbI72Mc7bdo4wBQFrCi2t0fGbWXGTcEpKWsPM62ARcFZ1++/u7TWG53qegZaDP0pYhFIoEPj3DDcygrQFzsKOGYDHdAKoe2bCz4Q0tYjbnvmu1fHpcPemucKQ2f6fkFOqf5OdiGJh7g7eY1CkicIdOyU7IuJQZfak/uR7RVOBU50M4IcI+BwrA02JYDljSsqbH6ofUCOrm5ojmhdLl9fB1mP/4YvBJN65Udzc1G58jWv6gvNG9e+r8bnDMbHsmp1HE=
