language: r
cache: packages
dist: xenial
cran: https://demo.rstudiopm.com/all/__linux__/xenial/latest
env:
  TEST_R_WITH_ARROW: "TRUE"
  ARROW_USE_OLD_CXXABI: 1
before_install:
# Set this in .Rprofile for RSPM binary packages
- echo 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))' >> ~/.Rprofile.site
- sudo apt-get install -y gdb
# Download wheel
- wget https://github.com/ursa-labs/crossbow/releases/download/nightly-2019-09-18-0-travis-wheel-manylinux2010-cp27mu/pyarrow-0.14.0.dev572-cp27-cp27mu-manylinux2010_x86_64.whl
- unzip *.whl
- git clone --depth=1 https://github.com/apache/arrow.git
- cd arrow/r
before_script:
- export INCLUDE_DIR=$TRAVIS_BUILD_DIR/pyarrow/include
- export LIB_DIR=$TRAVIS_BUILD_DIR/pyarrow
- export LD_LIBRARY_PATH=$LIB_DIR
- R -e 'install.packages("Rcpp", repo="https://cloud.r-project.org/")'
script:
- R CMD INSTALL --install-tests .
- R --debugger=gdb --debugger-args="-batch -x ../../bt.gdb" --slave -e 'library(testthat); setwd(file.path(.libPaths()[1], "arrow", "tests")); test_check("arrow", reporter="summary")'
