name: 'Update Check Run'
description: 'Find and update an associated check run with workflow status'
inputs:
  workflow-name:
    description: 'The name of the workflow to look for in check runs'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  job-status:
    description: 'The job status (success, failure, cancelled, etc.)'
    required: true
    default: ${{ job.status }}

runs:
  using: 'composite'
  steps:
    - name: Find associated check run
      id: find-check
      shell: bash
      run: |
        workflow_name="${{ inputs.workflow-name }}"
        head_sha="${{ github.sha }}"

        # Find check run with matching name pattern and head SHA
        check_run_id=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/commits/$head_sha/check-runs \
          --jq ".check_runs[] | select(.name == \"Manual: $workflow_name\") | .id" \
          | head -1)

        if [ -n "$check_run_id" ]; then
          echo "check_run_id=$check_run_id" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT
          echo "Found check run: $check_run_id"
        else
          echo "found=false" >> $GITHUB_OUTPUT
          echo "No associated check run found"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Update check run status
      if: steps.find-check.outputs.found == 'true'
      shell: bash
      run: |
        check_run_id="${{ steps.find-check.outputs.check_run_id }}"
        workflow_name="${{ inputs.workflow-name }}"
        job_status="${{ inputs.job-status }}"
        
        # Determine status based on job outcome
        if [ "$job_status" = "success" ]; then
          conclusion="success"
          title="Workflow Completed Successfully"
          summary="✅ The \`$workflow_name\` workflow completed successfully."
        elif [ "$job_status" = "failure" ]; then
          conclusion="failure"
          title="Workflow Failed"
          summary="❌ The \`$workflow_name\` workflow failed."
        elif [ "$job_status" = "cancelled" ]; then
          conclusion="cancelled"
          title="Workflow Cancelled"
          summary="⏹️ The \`$workflow_name\` workflow was cancelled."
        else
          conclusion="neutral"
          title="Workflow Completed"
          summary="The \`$workflow_name\` workflow completed with status: $job_status"
        fi

        # Update the check run
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/check-runs/$check_run_id \
          -f status="completed" \
          -f conclusion="$conclusion" \
          -f completed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          -f details_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f 'output[title]'="$title" \
          -f "output[summary]=$summary [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}