name: 'Hello World'
description: 'Greet someone'
inputs:
  name:
    description: 'Artifact to download'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
      continue-on-error: true
    - name: Download Artifact from main instead
      uses: dawidd6/action-download-artifact@v6
      if: github.event_name == 'pull_request' && failure()
      with:
        workflow: test.yml
        branch: main
        event: push
        name: ${{ inputs.name }}
    - name: Make sure at least one step passed
      run: |
        ${{ steps.download-artifact.outputs.artifact_name }} || ${{ steps.download-artifact-from-main.outputs.artifact_name }}

