name: 'Download artifact with fallback to main'
description: 'Download an artifact from the current run, or from the main branch if it does not exist. The fallback is only used when running on a pull request; when running on tags or the main branch, the artifact must exist in the current run. If using a fallback, an annotation is added to the run.'
inputs:
  name:
    description: 'Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.'
    required: false
  path:
    description: 'Destination path. Supports basic tilde expansion.'
    required: false
    default: "./"
  workflow:
    description: 'Name of the workflow that produced the artifact.'
    required: false
    default: test.yml
runs:
  using: "composite"
  steps:
    - name: Check if artifact exists on this run
      # Remove if https://github.com/actions/download-artifact/issues/352 happens
      uses: actions/github-script@v7
      id: check-artifact
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
            name: '${{ inputs.name }}'
          });
          // console.log(artifacts.data);
          core.setOutput('exists', artifacts.data.artifacts.length > 0);
    - name: Download Artifact
      id: download-local
      uses: actions/download-artifact@v4
      if: github.event_name != 'pull_request' || steps.check-artifact.outputs.exists == 'true'
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - name: Download Artifact from main instead
      id: download-main
      uses: dawidd6/action-download-artifact@v6
      if: github.event_name == 'pull_request' && steps.check-artifact.outputs.exists == 'false'
      with:
        workflow: ${{ inputs.workflow }}
        branch: main
        event: push
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - name: Add annotation if downloading from main
      run: |
        if [ ${{ steps.download-main.outcome }} = "success" ]; then
          echo "::notice title=${{ inputs.name }}::Downloaded from main"
        fi
      shell: bash

